### ISSUE TITLE
Karuta 2.2 Labelled as Karuta 2.0 in Welcome Page

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#104]
Karuta 2.2 portfolios say "Karuta 2.0" on the Welcome Page. Issue prensent in all 2.2 instances (savoie.hec.ca, eportfolium.fr and probably code available on GitHub).

**Comment by olivier-gerbe** [comment]
The Welcome Page Title is defined in _init.js. We forgot to change it in code. Sorry
