### ISSUE TITLE
Some block elements cannot be removed

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#108]
Dear all,

I have imported the block component templates: https://github.com/karutaproject/karuta-templates/blob/master/Blocks-Components/blocks-components.xml

The following components cannot be removed by any authorized role, *DocumentBlock*, *URLBlock*, *ImageBlock*, except the `designer`.

**Step to reproduce on a page**    
As a designer:
*add one the object mentioned above
*edit the created object and fill the role `Roles - delete`
*click the refresh icon
*switch to the related role

**Actual result**    
the delete icon is hidden

**Expected result**    
the delete icon is shown and the role can delete the object.

Best

Eric

**Comment by olivier-gerbe** [comment]
The problem has been fixed for the designer that changes roles. It was working for end user.
