### ISSUE TITLE
[Enhancement]: menu item separator

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#110]
Hi,
it would be nice to be able to add separators (ie. `<hr>` HTML tag) between the items of a custom menu, as it is done in the `Add` menu of a node.
Thanks
Eric

**Comment by olivier-gerbe** [comment]
Just write #line as menu items

**Comment by eviweb** [comment]
Thanks for the tip 😉 
best
Eric

**Comment by eviweb** [comment]
@olivier-gerbe,
is it possible to include a non clickable label to the section you created using the `#line` tag?
Thanks
Eric
