### ISSUE TITLE
[enhancement] : support of CSS classes in CSS Styles properties

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#114]
Hi,
currently only inline styles can be set in a resource `CSS Styles` settings.
It would be nice to be able to add CSS classes.
This would help in site customisation.
Eric

**Comment by olivier-gerbe** [comment]
Hi Eric,
Every element has the semantic tag added as a css class. So you can do customization based on semantic tag.

**Comment by eviweb** [comment]
Hi @olivier-gerbe,
yes this is a solution but it becomes a little bit tricky when you want to target specific elements between some having the same semantic tag.
And this solution does not apply to report tables for example.
Best
Eric

**Comment by olivier-gerbe** [comment]
In the new version you can add css styles in root metadata

**Comment by isabelle-roy** [comment]
Hi @eviweb,
The new css box in the metadata tab of the root element will now enable you to style using classes and id.
Try it out when 2.3 comes out and if this solution is satisfactory to you, please proceed to close this issue.
Thank you,
Isabelle (ePortfolium)
