### ISSUE TITLE
[enhancement] move portfolio to project

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#115]
Hi,
it would be useful to be able to move a portfolio from a project to another, without having to perform an export/import.
Moving it by drag & drop would be a Rolls Royce 😃
Eric

**Comment by olivier-gerbe** [comment]
Hi Éric
Just change the code of the portfolio. The first part is the code of the
project.
Olivier

**Comment by eviweb** [comment]
@olivier-gerbe
many thanks, it works well.
However it would be more intuitive to get an option in the actions dropdown menu of the portfolio or to have the possibility to move this item using drag & drop.
At least get an option that explicitly mentions this option in renaming the `Rename` option to something like `Rename/Move` along with a contextual help message next to the Code text field.
Best regards
Eric
