### ISSUE TITLE
[enhancement] Stucture & unit labels get from Get_Resource value

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#116]
Hi,
it would be very productive to permit sections, pages and subsections to get their labels automatically set, based on the value of a `Get_Resource`, `Get_Get_Resource`, or `Get_Double_Resource` object.
Eric

**Comment by olivier-gerbe** [comment]
It will be possible in version 2.3 using search as `Get_Resource`

**Comment by isabelle-roy** [comment]
Allo @olivier-gerbe, je ne comprends pas ce qu'il veut dire. Peux-tu m'expliquer pour que je puisse tester et fermer? Merci!

**Comment by olivier-gerbe** [comment]
Done. To be tested

**Comment by isabelle-roy** [comment]
Available in 2.3
