### ISSUE TITLE
Public URL malformed for domains containing the same word as the value of appliname

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#117]
Hi,
we experience an issue with public URLs.
Our site URL follows the format `karuta.domain.tld`.
The value of the `appliname` global variable defined in `/WebContent/application/js/_init.js` is left by default and its value is `karuta`. 
The problem comes from the following part of code of `./WebContent/karuta/js/karuta.js`:
```javascript
function sendEmailPublicURL(encodeddata,email,langcode) {
//==================================
	var url = window.location.href;
	var serverURL = url.substring(0,url.indexOf(appliname)-1);
	url = serverURL+"/"+appliname+"/application/htm/public.htm?i="+encodeddata+"&amp;lang="+languages[langcode];
```
and more precisely from: `var serverURL = url.substring(0,url.indexOf(appliname)-1);` which keeps all characters before the pattern `/appliname` in our case `/karuta` which results in `serverURL == "https:/"`.
The entire domain is stripped.
Eric

**Comment by olivier-gerbe** [comment]
Done.
