### ISSUE TITLE
The role 'all' does not reflect its intent

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#118]
Hi,
the role `all` does not reflect its intent.
By using this role when setting permissions on some items, we expect that these permissions apply to all the roles with which a portfolio is shared.
Unfortunately, this is not the case.
It seems that this role works as a fallback role and applies as any other roles.
This is particularly confusing when using the _Show To_ feature.
Maybe should it be renamed in something more explicit or the way it works should be changed.
Best regards
Eric

**Comment by olivier-gerbe** [comment]
Hi, the role `all` stands for everybody.

**Comment by eviweb** [comment]
Hi @olivier-gerbe,
you are right, but what it is disturbing is that it does not work as expected in designer mode.
Eric

**Comment by olivier-gerbe** [comment]
Sorry, but I don't understand. Can you give an example? Thanks. Olivier

**Comment by olivier-gerbe** [comment]
no response
