### ISSUE TITLE
Report CSV export not working

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#120]
Hi,
I created a report with a global table in which there are two rows:
- the first contains one cell with a `Text` item which values represents the title of the report
- the second row contains one cell with a `ForEachNode` item which iterates the data and build nested tables
While PDF and RTF exports correctly, the CSV export contains only one cell with the content of the `Text` item.
Eric

**Comment by eviweb** [comment]
I don't know if both problems are connected but sharing publicly the same report results in similar effect, only the first row is visible.
Eric

**Comment by olivier-gerbe** [comment]
Hi Eric,
CSV works only on not nested tables because we dont know how to interpret them.
