### ISSUE TITLE
[Enhancement] Report export keeps colors

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#121]
Hi,
currently PDF and RTF report exports are black/white even if the report is customized with some colors.
For example to alternate a background color between consecutive rows to facilitate the reading of a table.
I would be nice to keep these colors in the export.
Eric

**Comment by olivier-gerbe** [comment]
Done in version 2.3

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
I just tested this on our development karuta instance on eportfolium.fr server and not only is the report not in color, it does not have any of the formating (I used zebra-table to test and got regular table with borders) and worse the student data is not present!

**Comment by isabelle-roy** [comment]
Karuta 2.3 (release coming soonish!) offers the possibility to save tables as images (PNG).
