### ISSUE TITLE
Share Project as Regular User

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#127]
It is currently not possible to share a project in another role than designer, which means regular users have a menu to create portfolios even though they don't have a designer acount!!!

**Comment by olivier-gerbe** [comment]
When you create a project, there are two roles: all and designer. Maybe the role all has disappeared after importation. To be verified.

**Comment by isabelle-roy** [comment]
@olivier-gerbe 
This problem is still present in some projects.
You can verify this with "Modèles du projet Promising - phase 2" on eportfolium.fr, where there is no "all" to share the project with. 
This project was not imported but created on site. 
On the other hand, I just tested importing a project and the role all was available for sharing.

**Comment by olivier-gerbe** [comment]
Done. To be tested.
