### ISSUE TITLE
Problem with Semantic Tag when Translating Reports

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#128]
The semantic tag fields of reports is left blank in the secondary language. Semantic tags are unique, they do not change according to language, these fields should not be blank in the secondary language!
Same thing with the Test field - not language dependant, should not be blank.

**Comment by olivier-gerbe** [comment]
I agree for the semantic tag, not for the test. The test can be language dependent. However the code should be more complicated to handle that problem.
Here is a tip if you want to translate reports.
Edit the report root element and in metadata change the `display type` to `standard` , reload the report, in actions menu click on `Translate`. After edition change the  `display type` to `model`.
