### ISSUE TITLE
Cannot apply CSS Style to the welcome image

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#134]
Hi,
CSS styles set in the `Other CSS Instructions` of the `CSS Styles` tab of the `Welcome Image` don't apply because inline styles are already set in `UIFactory["Node"].displayWelcomePage()` function of the `./karuta/js/model/Type_Node.js` file.
The only way to deal with this issue is to specify styles in the `./application/css/specific.css` file, which prevents people that don't have access to their server to change CSS styles.
Best regards
Eric

**Comment by olivier-gerbe** [comment]
Fixed in version 3
In version 3, The welcome page will be a page like other one, so the css will be applied.
