### ISSUE TITLE
Dashboard and Batch data missing when switching between languages

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#138]
When switching to another language most data is missing from Dashboard and Batch portfolios.

In Dashboard portfolios the following fields are empty even though the data is not language dependent:
* the Test field
* the Semantic Tag field
* the Reference field

In the Batch portfolios, there is no data that is language dependent so all data should be present in all languages.

**Comment by olivier-gerbe** [comment]
Depending on which language is the default, the result may be empty. So we decided that all elements are multilingual
