### ISSUE TITLE
Create Batch Element for Delete User

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#139]

**Comment by olivier-gerbe** [comment]
Done. To be tested

**Comment by isabelle-roy** [comment]
@olivier-gerbe Not working - nothing happens. Please re-work this.

**Comment by olivier-gerbe** [comment]
@isabelle-roy - You need to be root - Only root can delete users

**Comment by isabelle-roy** [comment]
@olivier-gerbe I think if designers can create users through batch, they need to be able to undo through batch as well... ?
