### ISSUE TITLE
Modifying Label Font Size Blows Up Submitted/NotSubmitted Label

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#140]
Olivier, voir projet Alterkit sur savoie, *ePortfolio de gestion de projet - Isabelle/Mon projet final/Soumissions*. 
Pour le voir, tu dois te mettre dans le rôle Superviseur ou Coordinateur.

**Comment by isabelle-roy** [comment]
Olivier, le projet est déménagé sur le nouveau serveur, tu peux utiliser le ePortfolio de GP de Tintin comme exemple.

**Comment by olivier-gerbe** [comment]
Done. To be tested

**Comment by isabelle-roy** [comment]
OK- tested!
