### ISSUE TITLE
Share condition : submitted =='Y' don't work in 2.3 version 

### ISSUE THREAD

**Issue by japignon** [karutaproject/karuta-frontend#143]
The share is displayed well if submit has been validated  but ...
After clicking on the share, the notification by mail is not sent.

If instead of "submit == 'Y" we only write "submit", the condition is evaluated and the email notification is sent

**Comment by olivier-gerbe** [comment]
The test must be: submitted=='Y'
If the test is true, then the submit button is visible else it is not visible

**Comment by japignon** [comment]
sorry, for the mistake in my statement. It's good with submit == 'Y' that I found the problem and only with version 2.3

**Comment by japignon** [comment]
sorry, for the mistake in my statement due to google translator .... It's really with submitted == 'Y' that I found the problem and only with version 2.3
