### ISSUE TITLE
On template Ftlv karuta2.3 bug when deleting a lang

### ISSUE THREAD

**Issue by giraudin** [karutaproject/karuta-frontend#159]
When I test to add and delete a lang in europass into ftlv template eportfolium karuta 2.3 I have an error. See the screenshot below.

![bug ftlv europass suppression langue eportfolio com karuta 2 3](https://user-images.githubusercontent.com/7628798/46937590-f83db980-d061-11e8-8d51-d4759c9b32d0.png)

**Comment by olivier-gerbe** [comment]
Not able to reproduce as root or as a student

**Comment by giraudin** [comment]
Bonjour Olivier. Je suis sur eportfolium.com Karuta 2.3 je crée une nouvelle langue mais je ne rajoute rien en niveau et je supprime. Sur Firefox pc.
Eric 

⁣Envoyé par TypeApp ​

Le 15 oct. 2018 à 15:53, à 15:53, "Olivier Gerbé" <notifications@github.com> a écrit:

**Comment by olivier-gerbe** [comment]
Fixed
