### ISSUE TITLE
Configuration points for stylesheet, logo and "splash screen"

### ISSUE THREAD

**Issue by smkeesle** [karutaproject/karuta-frontend#16]
Allow a system admin a way to specify the CSS and content of the splash screen for Karuta. Since we have integrated Karuta into Sakai, it would be nice to white-label Karuta or style it like the LAMP Sakai instance. This would include a configuration point for a custom css file, html page, and logo.

**Comment by olivier-gerbe** [comment]
Code has been reorganized : application code and karuata-core code
