### ISSUE TITLE
Detailed Tutorial Not Found

### ISSUE THREAD

**Issue by sercanparker** [karutaproject/karuta-frontend#166]
Hi,

I want to run frontend, backend and fileserver projects on my local machine. I followed **Installing 
Karuta Source Code** title that exists in **ReadMe** file, however, when last step reached and localhost:8080/karuta entered on the browser, I got the HTTP 404 Not Found.

Is there any tutorial series that explain and figure these steps?

**Comment by olivier-gerbe** [comment]
Detailed instructions may be found at https://www.eportfolium.com/site/karuta_download_en.htm
