### ISSUE TITLE
CSS sur les pages publiques

### ISSUE THREAD

**Issue by Badatos** [karutaproject/karuta-frontend#175]
Bonjour,
Lorsque l'on partage une partie de son portfolio, celui à qui l'on partage reçoit une URL qui lui permet d'y accéder sans connexion, de ce type : 
karuta/application/htm/public.htm?i=9DB12DB0CBDFA...

Mais cette page ne reprend pas les CSS déclarées à la racine du portfolio. toutes les couleurs des menus sont celles par défaut, et les classes CSS ne sont pas applicables.

**Comment by olivier-gerbe** [comment]
Exact. Sauf si le portfolio entier est partagé, les classes déclarées au niveau de root ne sont pas disponibles. Ceci est du au fait que l'on ne charge que la portion partagée et non root.

**Comment by Badatos** [comment]
Merci pour l'explication, mais est-ce possible de modifier ce comportement ? pour la V3 ?
