### ISSUE TITLE
Menu des pages publiques trop grand sur mobiles

### ISSUE THREAD

**Issue by Badatos** [karutaproject/karuta-frontend#177]
Lorsqu'on affiche une page publique, sur un petit écran le menu prend une hauteur trop grande (tout l'écran) ce qui fait qu'il faut scroller beaucoup avant de voir le contenu.

Pour corriger, je préconise de retirer ce CSS :
```
.public-container #sidebar{
    height:100%;
}
```

**Comment by olivier-gerbe** [comment]
Sur un écran d'ordinateur cela donne un menu qui fait toute la hauteur de la fenêtre. On peut englober le css par @media screen and (min-width: 640px) { ... }

**Comment by Badatos** [comment]
Je n'ai pas réussi à voir le cas où le menu prendrait toute la hauteur sur grand écran. (ou en tout cas c'est déjà le cas aujourd'hui avec height:100% ;) ) mais en effet pourquoi pas le mettre en  @media screen and (min-width: 640px) si vous préférez.
