### ISSUE TITLE
impossible d'ajouter un Oembed sur la page de bienvenue

### ISSUE THREAD

**Issue by Badatos** [karutaproject/karuta-frontend#178]
Bonjour,
Lorsque j'ajoute une vidéo en Oembed sur la page de bienvenue d'un portfolio, elle s'affiche bien en mode "Édition" mais dès que je repasse en affichage normal le bloc ne s'affiche pas du tout.
J'ai rechargé la page, en vain.
Il n'y a aucune erreur dans la console du navigateur.

**Comment by olivier-gerbe** [comment]
Bonjour,
Pour qu'une ressource s'affiche dans la page de bienvenue, il faut que son tag sémantique contienne le mot welcome. Je pense qu'en mettant welcome-oembed comme tag sémantique, cela devrait fonctionner.

**Comment by Badatos** [comment]
En effet, ça fonctionne.
