### ISSUE TITLE
imposssible d'insérer de l'HTML (ou une barre oblique)dans le champ "Information" qui apparait en tooltip

### ISSUE THREAD

**Issue by Badatos** [karutaproject/karuta-frontend#179]
Bonjour,
Lorsque l'on entre du texte dans le champ "Information" qui apparait en tooltip, si on met de l'HTML (par exemple en utilisant le bouton "liste à puces" de l'interface), le texte qui apparaitra à l'utilisateur sera tronqué à la fin de la balise.

Il semble que ce soit lié au fait qu'il est impossible également de mettre une barre oblique ici (une balise fermante contenant toujours une barre oblique, exemple : </li> )

**Comment by olivier-gerbe** [comment]
Effectivement, le champ information ne supporte pas le html uniquement plain text.

**Comment by Badatos** [comment]
Le problème, c'est que ce champs est éditable en WYSIWYG, avec des boutons pour faire de la mise en forme HTML. Est-il prévu de retirer ces boutons dans la prochaine version pour éviter le bug ?
