### ISSUE TITLE
Problème sur les partages à l'intérieur d'un portfolio

### ISSUE THREAD

**Issue by eduquenoy** [karutaproject/karuta-frontend#196]
Lorsqu'on utilise la métadonnée "Partager", Karuta génère un lien vers le portfolio ou le morceau de portfolio à partager, qu'il envoie par email au destinataire. Cependant, la construction du lien se base sur le nom de l'application, "karuta" la plupart du temps. Si l'URL du serveur comporte également le nom de l'application, le lien n'est pas généré correctement. 
Par exemple, si l'on a "https://karuta.domainname.org/karuta/karuta/htm/karuta.htm", le nom de l'application étant "karuta", le premier "karuta" détecté sera celui qui est juste après "https://" et c'est donc "https://" qui sera utilisé comme URL et non "https://karuta.domainname.org/". Une solution ne serait-elle pas de faire une recherche sur le premier "/karuta/" et non pas sur le premier "karuta" ?

**Comment by olivier-gerbe** [comment]
Corrigé.
