### ISSUE TITLE
CAS not working

### ISSUE THREAD

**Issue by laurent6** [karutaproject/karuta-frontend#209]
Hello, 

CAS configuration is invalid. I follow the installation procedure: https://www.eportfolium.com/cooperative/application/htm/cooperative.htm to configurat cas but I've 404 error. The return casUrl is not correct. 

_init.js 
```
var application_version = "2.0";
var application_date = "2020-04-09";
//----------------------------------
var appliname = 'karuta';
var karutaname = 'karuta'; // to share the same 'karuta-core' with multiple front-end
var karuta_url = '../../../' + karutaname;
var bckname = '';
var serverBCK = "../../../karuta-backend"+bckname; // fileserver backend
var serverBCK_API = "../../../karuta-backend"+bckname+"/rest/api";
var cas_url = "https://my_cas_url";
```
 configKaruta.properties 
```
casCreateAccount=y
casUrlValidation=https://my_cas_url/serviceValidate
``` 
![image](https://user-images.githubusercontent.com/19220295/128187355-a5cef1fd-3597-4392-96c7-eb7b1b16f63f.png)

![image](https://user-images.githubusercontent.com/19220295/128187274-752e84de-7741-4756-a4b0-b7c1291f91e6.png)

We use 2.4.1 version to frontend. 
How correct this issue ?

**Comment by nobry** [comment]
I see that the redirection address is "/karuta/karuta-backend/{...}" when it should be "/karuta-backend/{...}"
Is there a redirection done somewhere?

**Comment by laurent6** [comment]
We haven't other redirect in tomcat.

**Comment by nobry** [comment]
When clicking on the "login from CAS" from the frontpage, check if the "service" parameter in the URL has the correct format "https://{your_server}/karuta-backend/rest/api/credential/login/cas"

If there's a "karuta" too much in front, check if "serverBCK_API" in _init.js has the default value "../../../karuta-backend"+bckname+"/rest/api"
