### ISSUE TITLE
Can't view portfolio from a sent email to a person without a user account

### ISSUE THREAD

**Issue by smkeesle** [karutaproject/karuta-frontend#36]
I shared a portfolio with a person (who isn't a user in te system) by their email.
The sent email has a link to see the portfolio like:

https://lamp.threecanoes.com/karuta/karuta/htm/public.htm?i=C1EB28B5CC8CA00FAED48A657A9F8C4FFB47B2F55CAFA9A4F655A0096817A346C7136B85CB6B238CB3589D4D5495EB3DC5ECC0AAD962F91374C946C0C2587788342219A2E01A1B44D8C8ED&lang=en

The link results in a view of Karuta that does NOT show the portfolio...and shows an error in the JS Console about not being able to load jquery (403 error):
https://lamp.threecanoes.com/karuta/other/js/jquery-1.10.2.js Failed to load resource: the server responded with a status of 403 (Forbidden)send @ jquery-1.10.2.js:8706
![screen shot 2016-08-31 at 6 21 46 pm](https://cloud.githubusercontent.com/assets/342735/18148489/e01eac3c-6fa7-11e6-90ed-62cd28e84e3a.png)

**Comment by olivier-gerbe** [comment]
Hi Sean,
Did you share the portfolio with public and the role all. A user not un the system is logged as public.

**Comment by jasmith1113** [comment]
We have now shared Terry Smith's showcase portfolio with public and the role all. There is a change in behavior. Now when I enter an email address for sharing the showcase portfolio and hit Send, nothing happens and the email is not sent.

**Comment by jasmith1113** [comment]
![showcase portfolio email not sent](https://cloud.githubusercontent.com/assets/9117518/18169894/c67d92f0-7021-11e6-8882-88bf9f0b8154.png)

**Comment by jasmith1113** [comment]
I mistakenly used the root account to share the showcase portfolio. When I used a user account (tsmith@nbts.edu), the email was sent and received, but the original problem of there being nothing in the portfolio persists.

**Comment by isabelle-roy** [comment]
Following Janice's comment above, here is the error in Firebug:

![lang undefined](https://cloud.githubusercontent.com/assets/1541128/18210452/8a5bf628-7106-11e6-81c3-b0812d38f5c7.PNG)
