### ISSUE TITLE
Portfolio Management Menu Bug

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#40]
Often when we click in the portfolio management menu, no action happens. **This problem is intermittent**, but when it is present no choice in the menu is active. Reloading the browser window is necessary to activate the menu options.

![1a e edit portfolio menu](https://cloud.githubusercontent.com/assets/1541128/18283913/9971f5ae-7435-11e6-8bba-57bb80890356.PNG)

**Comment by olivier-gerbe** [comment]
The menu was in inverted color and when clicked?
![capture d ecran 2016-09-14 a 17 08 25](https://cloud.githubusercontent.com/assets/8060484/18530121/08113380-7a9e-11e6-95fc-ae3c45f1bf91.jpg)

**Comment by isabelle-roy** [comment]
This problem has not occured recently - I am considering this issue as "sleeping" for now.
