### ISSUE TITLE
Europass

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#49]
* After choosing mother tongue, page must be redisplayed to be able change the language.
* In French, "S exprimer oralement en continu" should read "S&RSQUO;exprimer".
* "S exprimer oralement en continu", "Spoken Interaction" and "Spoken Production" should have &NBSP; before and after so they are easier to read.
* Ordering languages alphabetically would also make it easier to read.
* Ordering levels of proficiency with A as best proficiency and C as least proficiency would be more logical.

**Comment by olivier-gerbe** [comment]
The first three issues are fixed.
Languages are ordering by their ISO code. Ordering languages alphabetically is depending of the language.
Levels of proficiency are given the the Europass standard.

**Comment by isabelle-roy** [comment]
Tested by Isabelle, OK for 2.2 release
