### ISSUE TITLE
Zebra-style Table

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#53]
Create a predefined css option for zebra tables:
tr:nth-child(even) {background-color: #e6e6e6}
td {border: 0px solid white; padding: 10px;}

![issue 6](https://cloud.githubusercontent.com/assets/1541128/19778495/02afcfae-9c4b-11e6-877b-9fffa17d959b.PNG)

**Comment by olivier-gerbe** [comment]
Done
