### ISSUE TITLE
Roles not created automatically

### ISSUE THREAD

**Issue by jasmith1113** [karutaproject/karuta-frontend#75]
After adding a new role to the metadata screen for a particular resource, we tried to share the portfolio with a user using the new role, but the role did not appear on the share screen.  Version 2.1

**Comment by darolmar** [comment]
Can anybody tell me in what database table roles are stored, please? I would like to check if SQL is invoked.  Thanks so much in advance!

**Comment by olivier-gerbe** [comment]
Roles are set in model and corresponding groups are created when portfolios are instantiated. You cannot add a new role after instantiation.

**Comment by darolmar** [comment]
Here you have the steps Janice and me have followed to reproduce:
1. Edit a porfolio item. For example, the Evidence described at Workbook #1 
2. At metadata tab, type 'observer' in Roles-showtoroles
3. Close the popup
4. Go to Home page
5. In the dropdown menu of the project or of one of the portfolios, select "Share with a User"
6. In the popup, 'observer' should be at Roles section. But it's not there. :(

**Comment by olivier-gerbe** [comment]
If it is in the design process (as a designer) You need to reload the portfolio. Roles are scanned at loading.

**Comment by darolmar** [comment]
I log in as designer or root (results are the same). I edit a model portfolio and a portfolio Item (the Evidence of the woorkbook):
![karuta01](https://cloud.githubusercontent.com/assets/8734228/21449343/86c918b8-c8ec-11e6-82c7-1450d5ac00bf.JPG)
Then to the home page and press reload button:
![karuta01b](https://cloud.githubusercontent.com/assets/8734228/21449352/9457dad2-c8ec-11e6-9641-155ad8b414f5.JPG)
In the select drop down menu, I choose "share with users":
![karuta02](https://cloud.githubusercontent.com/assets/8734228/21449360/b58fcef8-c8ec-11e6-93ac-631a76d08dab.png)
And I cannot see 'observer' role at the role section:
![karuta03](https://cloud.githubusercontent.com/assets/8734228/21449371/c6c99c1c-c8ec-11e6-83fc-1670bc676d40.JPG)

Am I doing something wrong? Remember I'm newbie a Karuta so, that quite, probable, I'm afraid. 

Thanks!

**Comment by darolmar** [comment]
I've doing further testing and new role appears when trying to share a portfolio model instance but not when trying to share the original portfolio model. Is this right?

**Comment by olivier-gerbe** [comment]
Hi David,

Yes. Portfolio Model has no rights groups. Only instances have groups. And you can add a group after instantiation.

Olivier

**Comment by olivier-gerbe** [comment]
Not an issue
