### ISSUE TITLE
Login page is not loaded properly because some js scripts are not found (404 error)

### ISSUE THREAD

**Issue by darolmar** [karutaproject/karuta-frontend#77]
[karuta-frontend.txt](https://github.com/karutaproject/karuta-frontend/files/675247/karuta-frontend.txt)
When loading frontend login page with this code:
![imagen](https://cloud.githubusercontent.com/assets/8734228/21517320/7b9a3f3a-ccde-11e6-922a-40cfac0c4b7b.png)
I'm always getting the same results:
![imagen](https://cloud.githubusercontent.com/assets/8734228/21517332/90fa7f5c-ccde-11e6-813a-2b6a15487c1b.png)
This is due the lack of availability of some js files when login.js is loaded. To fix this, theses files should be loaded before login.js so that when displayKarutaLogin() is invoked they have been already loaded:
![imagen](https://cloud.githubusercontent.com/assets/8734228/21517489/ecf006c8-ccdf-11e6-91c2-a06a62f995d3.png)
If we do like this, we'll get the login page rendered:
![imagen](https://cloud.githubusercontent.com/assets/8734228/21517501/04ea1778-cce0-11e6-9baa-e1a9a1c22231.png)

I'm attaching a patch to fix this.

**Comment by olivier-gerbe** [comment]
Very strange because this was working on different servers and different browser for two or three months.

**Comment by darolmar** [comment]
I would suggest to try to reproduce from a fresh installation. I have the same problem each time I reset to the main brach.
