### ISSUE TITLE
GGR Options Not Presented in Correct Order

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#80]
I have this problem when there is a middle level in the structure that is not used:
* C1 (Unit)
  * C1.1 (UnitStructure)
    * C1.1.1 (Item)
     * C1.1.2 (Item)
  * C1.2 (UnitStructure)
    * C1.2.1 (Item)
    * C1.2.2 (Item)

GR calls on Units and GGR calls on all Items of this Unit.

**Comment by isabelle-roy** [comment]
I have tested this issue again today and it is still a problem. Please fix for 2.3 release.

**Comment by olivier-gerbe** [comment]
Done. To be tested

**Comment by isabelle-roy** [comment]
Tested - All good.
