### ISSUE TITLE
Managing Roles in Instances

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#81]
This is done through a matrix with checkboxes for read and write roles, but it doesn't work for submit role: in that particular case the role has to be removed from the field below (an action which is ineffective for other roles). Please choose one method and make all the same.

**Comment by olivier-gerbe** [comment]
Submit is not a right. So there is no checkbox for that. If the user has write right and the user role is in submitroles, the user can submit.
