### ISSUE TITLE
Menus Don't Work When Multiple Semantic Tags

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#84]
Menus don't work if there are multiple semantic tags on the part to be pasted.

**Comment by isabelle-roy** [comment]
I have tested this issue again today and it is still a problem. Please fix for 2.3 release.

**Comment by olivier-gerbe** [comment]
Done. To be tested.

**Comment by isabelle-roy** [comment]
Tested & approved!

**Comment by isabelle-roy** [comment]
Not possible after all. This issue is abandonned.

**Comment by nobry** [comment]
It could be done with a regexp function in Mysql. I need to check the Mysql version used since this function appeared in version 5.6.
And it could be done with something less pretty with basic SQL functions.

You can put it in improvements if needed rather than bug.

**Comment by isabelle-roy** [comment]
OK!
