### ISSUE TITLE
Instance Roles in Imported Projects

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#92]
The instances of an imported project do not have the sharing or even the role to re-do the sharing. This is a big problem when we move a project in production stage to another server.

**Comment by isabelle-roy** [comment]
I have tried importing the project through the function "Import portfolio instance .zip" and still the instances are not shared (the roles exist but the sharing is not done).
We need to be able to move projects without re-sharing all the student portfolios. (The move of nbts is coming up and the number of shares is in the high 3 or even 4 digits!)

**Comment by olivier-gerbe** [comment]
Not a good idea
