### ISSUE TITLE
Menu for Different User Roles

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#95]
A menu with two options for two different user roles (one option for each role) is displayed as a Menu button with a single option for each role instead of a direct clickable option (which is usually the case when only one option is available to a user).

**Comment by olivier-gerbe** [comment]
Done. Tob tested

**Comment by isabelle-roy** [comment]
Resolved for the first role, not for the subsequent ones (they still get the Menu button).

**Comment by olivier-gerbe** [comment]
Done. to be tested

**Comment by isabelle-roy** [comment]
Ok in 2.3
