### ISSUE TITLE
Errors in Templates for New Languages

### ISSUE THREAD

**Issue by isabelle-roy** [karutaproject/karuta-frontend#96]
For Sharing and Menus (metadata tab of a structural element).

**Comment by isabelle-roy** [comment]
This issue is still a problem. Please fix for 2.3 release.

**Comment by isabelle-roy** [comment]
Templates for Sharing, Menus and Additional information have @en tag for Español and Valencià.
Person who created these versions of Karuta, please make correction.

**Comment by olivier-gerbe** [comment]
Español and Valencià languages are not part of the current version.
